export const REGISTER_SUCCESS = 'REGISTER/REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER/REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN/LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN/LOGIN_FAIL'
export const LOG_OUT = 'LOGIN/LOG_OUT'

export const LOADING = 'LOADING'
export const SET_ERROR = 'ERROR/SET_ERROR'
export const CLEAR_ERROR = 'ERROR/CLEAR_MESSAGE'
export const SET_MESSAGE = 'MESSAGE/SET_MESSAGE'
export const CLEAR_MESSAGE = 'MESSAGE/CLEAR_MESSAGE'

export const FETCH_QUERY = 'SEARCH/FETCH_QUERY'
export const FETCH_QUERY_SUCCESS = 'SEARCH/FETCH_QUERY_SUCCESS'
export const FETCH_QUERY_ERROR = 'SEARCH/FETCH_QUERY_ERROR'

export const FETCH_CHANGE_QUERY = 'SEARCH/FETCH_CHANGE_QUERY'
